/*==============================================================*/
/* DBMS name:      Microsoft SQL Server 2017                    */
/* Created on:     5/26/2019 3:44:39 AM                         */
/*==============================================================*/


IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TB_JAF_AZIZ_EVENT_LOG_FS')
            AND   TYPE = 'U')
   DROP TABLE TB_JAF_AZIZ_EVENT_LOG_FS
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TB_JAF_AZIZ_EVENT_TYPE_FS')
            AND   TYPE = 'U')
   DROP TABLE TB_JAF_AZIZ_EVENT_TYPE_FS
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TB_JAF_AZIZ_REGION_FS')
            AND   TYPE = 'U')
   DROP TABLE TB_JAF_AZIZ_REGION_FS
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_PLANO')
            AND   TYPE = 'U')
   DROP TABLE TB_JAF_AZIZ_REPORT_TRANSAC_DAY_PLANO
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_SALES')
            AND   TYPE = 'U')
   DROP TABLE TB_JAF_AZIZ_REPORT_TRANSAC_DAY_SALES
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_MONTH_PLANO')
            AND   TYPE = 'U')
   DROP TABLE TB_JAF_AZIZ_REPORT_TRANSAC_MONTH_PLANO
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_MONTH_SALES')
            AND   TYPE = 'U')
   DROP TABLE TB_JAF_AZIZ_REPORT_TRANSAC_MONTH_SALES
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TB_JAF_AZIZ_TERRITORY_FS')
            AND   TYPE = 'U')
   DROP TABLE TB_JAF_AZIZ_TERRITORY_FS
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TB_JAF_AZIZ_TRANSACTION_FS')
            AND   TYPE = 'U')
   DROP TABLE TB_JAF_AZIZ_TRANSACTION_FS
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TB_JAF_AZIZ_TRANSACTION_TYPE_FS')
            AND   TYPE = 'U')
   DROP TABLE TB_JAF_AZIZ_TRANSACTION_TYPE_FS
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TB_JAF_AZIZ_USER_ANSWER_FS')
            AND   TYPE = 'U')
   DROP TABLE TB_JAF_AZIZ_USER_ANSWER_FS
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TB_JAF_AZIZ_USER_ME_FS')
            AND   TYPE = 'U')
   DROP TABLE TB_JAF_AZIZ_USER_ME_FS
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TB_JAF_AZIZ_USER_POS_FS')
            AND   TYPE = 'U')
   DROP TABLE TB_JAF_AZIZ_USER_POS_FS
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TB_JAF_AZIZ_USER_QUIZ_FS')
            AND   TYPE = 'U')
   DROP TABLE TB_JAF_AZIZ_USER_QUIZ_FS
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TB_JAF_AZIZ_USER_SUP_FS')
            AND   TYPE = 'U')
   DROP TABLE TB_JAF_AZIZ_USER_SUP_FS
go

ISQL TB_JAF_AZIZ_EVENT_LOG_FS.sql
go

ISQL TB_JAF_AZIZ_EVENT_TYPE_FS.sql
go

ISQL TB_JAF_AZIZ_REGION_FS.sql
go

ISQL TB_JAF_AZIZ_REPORT_TRANSAC_DAY_PLANO.sql
go

ISQL TB_JAF_AZIZ_REPORT_TRANSAC_DAY_SALES.sql
go

ISQL TB_JAF_AZIZ_REPORT_TRANSAC_MONTH_PLANO.sql
go

ISQL TB_JAF_AZIZ_REPORT_TRANSAC_MONTH_SALES.sql
go

ISQL TB_JAF_AZIZ_TERRITORY_FS.sql
go

ISQL TB_JAF_AZIZ_TRANSACTION_FS.sql
go

ISQL TB_JAF_AZIZ_TRANSACTION_TYPE_FS.sql
go

ISQL TB_JAF_AZIZ_USER_ANSWER_FS.sql
go

ISQL TB_JAF_AZIZ_USER_ME_FS.sql
go

ISQL TB_JAF_AZIZ_USER_POS_FS.sql
go

ISQL TB_JAF_AZIZ_USER_QUIZ_FS.sql
go

ISQL TB_JAF_AZIZ_USER_SUP_FS.sql
go

