--- Database name:  	DB_VYB_DMA
--- DBMS name:      	Microsoft SQL Server 2017
--- Created on:     	6/12/2019 9:42:18 AM
--- Project Name:	TALOS Integration & Reporting
--- Application:	VyB (Visualize Your Business)
--- DB Layer:		DMA
--- DB Name:		DB_VYB_DMA
--- Author:		Florian Nicolas (External)
--- Description:	Creation of the table TB_VYB_FACT_AMNT_POINT_H 
--------------------------------------------------------------------
----- STATEMENT DROP TABLE AND SYNONYM IF EXIST
USE DB_VYB_DMA
GO
IF OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H', 'U') IS NOT NULL
DROP TABLE TB_VYB_FACT_AMNT_POINT_H
IF OBJECT_ID('SYN_TB_VYB_FACT_AMNT_POINT_H', 'SN') IS NOT NULL
DROP SYNONYM SYN_TB_VYB_FACT_AMNT_POINT_H
IF OBJECT_ID('PK_TB_VYB_FACT_AMNT_POINT_H', 'PK') IS NOT NULL
ALTER TABLE TB_VYB_FACT_AMNT_POINT_H DROP CONSTRAINT PK_TB_VYB_FACT_AMNT_POINT_H;
GO
----- STATEMENT CREATE TABLE
USE DB_VYB_DMA
GO
CREATE TABLE TB_VYB_FACT_AMNT_POINT_H (
   SR_KEY_USER_POS      	INT 			NULL,
   SR_KEY_USER_SUP      	INT			NULL,
   SR_KEY_USER_ME       	INT			NULL,
   SR_KEY_DT_CRT_TRANSAC 	INT                  	NULL,
   SR_KEY_DT_UPD_TRANSAC 	INT                  	NULL,
   SR_KEY_DT_CRT_USER_POS 	INT                  	NULL,
   SR_KEY_DT_UPD_USER_POS 	INT                  	NULL,
   SR_KEY_DT_CRT_USER_ME 	INT                  	NULL,
   SR_KEY_DT_UPD_USER_ME 	INT                  	NULL,
   SR_KEY_DT_CRT_USER_SUP 	INT                  	NULL,
   SR_KEY_DT_UPD_USER_SUP 	INT                  	NULL,
   SR_KEY_LOCATION_USER_POS 	INT                  	NULL,
   SR_KEY_LOCATION_USER_ME 	INT                 	NULL,
   SR_KEY_LOCATION_USER_SUP 	INT                  	NULL,
   SR_KEY_UNIT_TYPE     	INT                  	NULL,
   SR_KEY_TRANSACTION_TYPE 	INT                  	NULL,
   SR_KEY_EVENT_TYPE    	INT                  	NULL,
   AMNT_POINT           	NUMERIC(10,3)        	NULL,
   TK_KEY_REFERENCE_DATE 	DATE                 	NULL,
   TK_KEY_AUDIT_PROCESS_ID 	INT                  	NULL,
   TK_KEY_INL_PPN_TMS   	SMALLDATETIME		NULL,
   TK_KEY_UNQ_ID_SRC_STM 	VARCHAR(256)		NULL
)
GO
IF EXISTS (SELECT 1 FROM  SYS.EXTENDED_PROPERTIES
           WHERE MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H') AND MINOR_ID = 0)
BEGIN 
   DECLARE @CURRENTUSER SYSNAME 
SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description',  
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H' 
END 
SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description',  
   '- Client Name: Philip Morris International
   - Client Location: Dubai (UAE)
   - Application Name: VyB (Visualize Your Business)
   - Client Location: Dubai (UAE)
   - Application Description: VyB is BI application that enable to load internal PMI data from the source system to last DB layer in order to build data reports and interactive data visualization applications. The data reports and data visualizations applications are developed for internal use.
   - Component Type: Entity
   - Component Name: Table Fact Amount Point
   - Specific Project / Application Source Code: TALOS', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_USER_POS')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_USER_POS'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key User',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_USER_POS'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_USER_SUP')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_USER_SUP'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key User Superior',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_USER_SUP'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_USER_ME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_USER_ME'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key User ME',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_USER_ME'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_DT_CRT_TRANSAC')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_CRT_TRANSAC'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key Date Creation Transaction',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_CRT_TRANSAC'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_DT_UPD_TRANSAC')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_UPD_TRANSAC'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key Date Update Transaction',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_UPD_TRANSAC'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_DT_CRT_USER_POS')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_CRT_USER_POS'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key Date Creation User POS',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_CRT_USER_POS'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_DT_UPD_USER_POS')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_UPD_USER_POS'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key Date Update User POS',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_UPD_USER_POS'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_DT_CRT_USER_ME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_CRT_USER_ME'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key Date Creation User ME',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_CRT_USER_ME'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_DT_UPD_USER_ME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_UPD_USER_ME'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key Date Creation User Superior',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_UPD_USER_ME'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_DT_CRT_USER_SUP')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_CRT_USER_SUP'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key Date Update User Superior',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_CRT_USER_SUP'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_DT_UPD_USER_SUP')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_UPD_USER_SUP'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key Location User Point of Sale',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_DT_UPD_USER_SUP'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_LOCATION_USER_POS')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_LOCATION_USER_POS'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key Location User Point of Sale',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_LOCATION_USER_POS'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_LOCATION_USER_ME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_LOCATION_USER_ME'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key Location User ME',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_LOCATION_USER_ME'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_LOCATION_USER_SUP')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_LOCATION_USER_SUP'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key Location User Superior',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_LOCATION_USER_SUP'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_UNIT_TYPE')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_UNIT_TYPE'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key Unit Type',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_UNIT_TYPE'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_TRANSACTION_TYPE')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_TRANSACTION_TYPE'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key Transaction Type',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_TRANSACTION_TYPE'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_EVENT_TYPE')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_EVENT_TYPE'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key Event Type',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'SR_KEY_EVENT_TYPE'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'AMNT_POINT')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'AMNT_POINT'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Amount Point',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'AMNT_POINT'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TK_KEY_REFERENCE_DATE')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'TK_KEY_REFERENCE_DATE'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Technical Key Accumulating Snapshot Reference Date',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'TK_KEY_REFERENCE_DATE'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TK_KEY_AUDIT_PROCESS_ID')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'TK_KEY_AUDIT_PROCESS_ID'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Technical Key Audit Process Identifier',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'TK_KEY_AUDIT_PROCESS_ID'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TK_KEY_INL_PPN_TMS')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'TK_KEY_INL_PPN_TMS'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Technical Key Creation Timestamp',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'TK_KEY_INL_PPN_TMS'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_FACT_AMNT_POINT_H')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TK_KEY_UNQ_ID_SRC_STM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'TK_KEY_UNQ_ID_SRC_STM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Technical Key Unique Identifier of Source Stream',
   'user', @CURRENTUSER, 'table', 'TB_VYB_FACT_AMNT_POINT_H', 'column', 'TK_KEY_UNQ_ID_SRC_STM'
GO
/*==============================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_USER_POS_FK */
/*==============================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_USER_POS_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_USER_POS ASC)
GO
/*===================================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_USER_SUPERIOR_FK */
/*===================================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_USER_SUPERIOR_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_USER_SUP ASC)
GO
/*==============================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_USER_ME_FK  */
/*==============================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_USER_ME_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_USER_ME ASC)
GO
/*======================================================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_CREATION_TRANSACTION_FK */
/*======================================================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_CREATION_TRANSACTION_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_DT_CRT_TRANSAC ASC)
GO
/*====================================================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_UPDATE_TRANSACTION_FK */
/*====================================================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_UPDATE_TRANSACTION_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_DT_UPD_TRANSAC ASC)
GO
/*===================================================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_CREATION_USER_POS_FK */
/*===================================================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_CREATION_USER_POS_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_DT_CRT_USER_POS ASC)
GO
/*=================================================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_UPDATE_USER_POS_FK */
/*=================================================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_UPDATE_USER_POS_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_DT_UPD_USER_POS ASC)
GO
/*==================================================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_CREATION_USER_ME_FK */
/*==================================================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_CREATION_USER_ME_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_DT_CRT_USER_ME ASC)
GO
/*================================================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_UPDATE_USER_ME_FK */
/*================================================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_UPDATE_USER_ME_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_DT_UPD_USER_ME ASC)
GO
/*===================================================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_CREATION_USER_SUP_FK */
/*===================================================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_CREATION_USER_SUP_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_DT_CRT_USER_SUP ASC)
GO
/*========================================================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_CREATION_USER_SUPERIOR_FK */
/*========================================================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_DATE___DATE_CREATION_USER_SUPERIOR_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_DT_UPD_USER_SUP ASC)
GO
/*=========================================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_LOCATION___USER_POS_FK */
/*=========================================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_LOCATION___USER_POS_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_LOCATION_USER_POS ASC)
GO
/*========================================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_LOCATION___USER_ME_FK */
/*========================================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_LOCATION___USER_ME_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_LOCATION_USER_ME ASC)
GO
/*=========================================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_LOCATION___USER_SUP_FK */
/*=========================================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_LOCATION___USER_SUP_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_LOCATION_USER_SUP ASC)
GO
/*===============================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_UNIT_TYPE_FK */
/*===============================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_UNIT_TYPE_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_UNIT_TYPE ASC)
GO
/*======================================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_TRANSACTION_TYPE_FK */
/*======================================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_TRANSACTION_TYPE_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_TRANSACTION_TYPE ASC)
GO
/*================================================================*/
/* Index: LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_EVENT_TYPE_FK */
/*================================================================*/
CREATE NONCLUSTERED INDEX LINK_TABLE_FACT_AMOUNT_POINT_TO_TABLE_DIM_EVENT_TYPE_FK ON TB_VYB_FACT_AMNT_POINT_H (SR_KEY_EVENT_TYPE ASC)
GO
----- STATEMENT CREATE TABLE
CREATE SYNONYM SYN_TB_VYB_FACT_AMNT_POINT_H FOR TB_VYB_FACT_AMNT_POINT_H
GO