--- Database name:  	DB_VYB_ODS_TALOS
--- DBMS name:      	Microsoft SQL Server 2017
--- Created on:     	5/19/2019 2:42:18 AM
--- Project Name:	TALOS Integration & Reporting
--- Application:	VyB (Visualize Your Business)
--- DB Layer:		ODS
--- DB Name:		DB_VYB_ODS_TALOS
--- Author:		Florian Nicolas (External)
--- Description:	Creation of the table TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL
--------------------------------------------------------------------
----- TO RUN NOT THE FIRST TIME OF EXECUTION 
USE DB_VYB_ODS_TALOS
GO
IF OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'U') IS NOT NULL
DROP TABLE dbo.TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL
DROP SYNONYM SYN_TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL
GO
USE DB_VYB_ODS_TALOS
GO
----- TO RUN EVERYTIME CREATE TABLE STATEMENT
CREATE TABLE TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL (
   TRANSACTION_ID       VARCHAR(256)         NOT NULL,
   TRANSACTION_USER_ID  VARCHAR(256)         NULL,
   POS_USER_BUSINESS_NM NTEXT                NULL,
   POS_USER_REGION_NM   VARCHAR(256)         NULL,
   POS_USER_TERRITORY_NM VARCHAR(256)         NULL,
   POS_USER_COUNTRY_NM  VARCHAR(256)         NULL,
   POS_USER_PRIORITY_CD VARCHAR(256)         NULL,
   ME_USER_OWNER_SURNAME_NM VARCHAR(256)         NULL,
   TRANSACTION_AMNT     NUMERIC(10,3)        NULL,
   TRANSACTION_DT       SMALLDATETIME        NULL,
   TRANSACTION_TYPE_NM  VARCHAR(256)         NULL,
   TRANSACTION_UNIT_TYPE_NM VARCHAR(256)         NULL,
   TRANSACTION_EVENT_TYPE_ID VARCHAR(256)         NULL,
   TRANSACTION_DT_YEAR  VARCHAR(256)         NULL,
   TRANSACTION_DT_MONTH VARCHAR(256)         NULL,
   TRANSACTION_DT_DAY   VARCHAR(256)         NULL,
   CONSTRAINT PK_TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL PRIMARY KEY (TRANSACTION_ID)
)
GO
IF EXISTS (SELECT 1 FROM  SYS.EXTENDED_PROPERTIES
           WHERE MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL') AND MINOR_ID = 0)
BEGIN 
   DECLARE @CURRENTUSER SYSNAME 
SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description',  
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL' 
END 
SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description',  
   '- Client Name: Philip Morris International
   - Client Location: Dubai (UAE)
   - Application Name: VyB (Visualize Your Business)
   - Client Location: Dubai (UAE)
   - Application Name: VyB (Visual Your Business)
   - Application Description: VyB is BI application that enable to load internal PMI data from the source system to last DB layer in order to build data reports and interactive data visualization applications. The data reports and data visualizations applications are developed for internal use.
   
   - Component Type: Table
   - Component Name: TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL
   - Component Description: Transactional Table Sales Points / Daily', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TRANSACTION_ID')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_ID'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Transaction Identifier',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_ID'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TRANSACTION_USER_ID')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_USER_ID'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Transaction User Identifier',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_USER_ID'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'POS_USER_BUSINESS_NM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'POS_USER_BUSINESS_NM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Business Name',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'POS_USER_BUSINESS_NM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'POS_USER_REGION_NM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'POS_USER_REGION_NM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Region Identifier',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'POS_USER_REGION_NM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'POS_USER_TERRITORY_NM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'POS_USER_TERRITORY_NM'

END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Territory Name',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'POS_USER_TERRITORY_NM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'POS_USER_COUNTRY_NM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'POS_USER_COUNTRY_NM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'POS User Country Name',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'POS_USER_COUNTRY_NM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'POS_USER_PRIORITY_CD')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'POS_USER_PRIORITY_CD'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Priority Code',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'POS_USER_PRIORITY_CD'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'ME_USER_OWNER_SURNAME_NM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'ME_USER_OWNER_SURNAME_NM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Surname Name',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'ME_USER_OWNER_SURNAME_NM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TRANSACTION_AMNT')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_AMNT'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Transaction Amount',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_AMNT'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TRANSACTION_DT')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_DT'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Transaction Date',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_DT'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TRANSACTION_TYPE_NM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_TYPE_NM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Transaction Type Name',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_TYPE_NM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TRANSACTION_UNIT_TYPE_NM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_UNIT_TYPE_NM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Event Identifier',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_UNIT_TYPE_NM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TRANSACTION_EVENT_TYPE_ID')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_EVENT_TYPE_ID'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Transaction Event Type Identifier',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_EVENT_TYPE_ID'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TRANSACTION_DT_YEAR')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_DT_YEAR'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Transaction Date Year',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_DT_YEAR'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TRANSACTION_DT_MONTH')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_DT_MONTH'

END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Transaction Date Month',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_DT_MONTH'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TRANSACTION_DT_DAY')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_DT_DAY'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Transaction Date Day',
   'user', @CURRENTUSER, 'table', 'TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL', 'column', 'TRANSACTION_DT_DAY'
GO
------ SYNONYM
CREATE SYNONYM SYN_TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL FOR TB_JAF_AZIZ_REPORT_TRANSAC_DAY_AVAIL
GO