--- Database name:  	DB_VYB_DMA
--- DBMS name:      	Microsoft SQL Server 2017
--- Created on:     	6/12/2019 9:42:18 AM
--- Project Name:	TALOS Integration & Reporting
--- Application:	VyB (Visualize Your Business)
--- DB Layer:		DMA
--- DB Name:		DB_VYB_DMA
--- Author:		Florian Nicolas (External)
--- Description:	Creation of the table TB_VYB_AUDIT_PROCESS
--------------------------------------------------------------------
----- STATEMENT DROP TABLE AND SYNONYM IF EXIST (NOT TO EXECUTION AT THE 1ST TIME OF EXECUTION)
USE DB_VYB_DMA
GO
IF OBJECT_ID('TB_VYB_DMA_AUDIT_PROCESS ', 'U') IS NOT NULL
DROP TABLE TB_VYB_DMA_AUDIT_PROCESS
IF OBJECT_ID('SYN_TB_VYB_DMA_AUDIT_PROCESS ', 'SN') IS NOT NULL
DROP SYNONYM SYN_TB_VYB_DMA_AUDIT_PROCESS
IF OBJECT_ID('PK_TB_VYB_DMA_AUDIT_PROCESS ', 'PK') IS NOT NULL
ALTER TABLE TB_VYB_DMA_AUDIT_PROCESS DROP CONSTRAINT PK_TB_VYB_DMA_AUDIT_PROCESS;
GO
----- STATEMENT CREATE TABLE (TO EXECUTE EVERYTIME / AT EACH EXECUTION OF THE SCRIPT)
USE DB_VYB_DMA
GO
CREATE TABLE TB_VYB_DMA_AUDIT_PROCESS (
   AUDIT_PROCESS_ID     		INT                  NOT NULL,
   CONTAINER_START_TIME 		VARCHAR(256)         NULL,
   CREATION_DATE        		VARCHAR(256)         NULL,
   CREATION_NAME        		VARCHAR(256)         NULL,
   CREATOR_COMPUTER_NAME 		VARCHAR(256)         NULL,
   CREATOR_NAME         		VARCHAR(256)         NULL,
   EXECUTION_INSTANCE_GUID 		VARCHAR(256)         NULL,
   FAILED_CONFIGURATION 		VARCHAR(256)         NULL,
   IGNORE_CONFIGURATION_ON_LOAD 	VARCHAR(256)         NULL,
   INTERACTIVE_MODE     		VARCHAR(256)         NULL,
   LAST_MODIFIED_PRODUCT_VERSION 	VARCHAR(256)         NULL,
   LOCALE_ID            		VARCHAR(256)         NULL,
   MACHINE_NAME         		VARCHAR(256)         NULL,
   OFFLINE_MODE         		VARCHAR(256)         NULL,
   PACKAGE_ID           		VARCHAR(256)         NULL,
   PACKAGE_NAME         		VARCHAR(256)         NULL,
   PARENT_CONTAINER_GUID 		VARCHAR(256)         NULL,
   PRODUCT_VERSION      		VARCHAR(256)         NULL,
   SERVER_EXECUTION_ID  		VARCHAR(256)         NULL,
   START_TIME           		VARCHAR(256)         NULL,
   TASK_ID              		VARCHAR(256)         NULL,
   TASK_NAME            		VARCHAR(256)         NULL,
   TASK_TRANSACTION_OPTION 		VARCHAR(256)         NULL,
   USER_NAME            		VARCHAR(256)         NULL,
   VERSION_BUILD        		VARCHAR(256)         NULL,
   VERSION_COMMENTS     		VARCHAR(256)         NULL,
   VERSION_GUID         		VARCHAR(256)         NULL,
   VERSION_MAJOR        		VARCHAR(256)         NULL,
   VERSION_MINOR        		VARCHAR(256)         NULL,
   CONSTRAINT PK_TB_VYB_DMA_AUDIT_PROCESS PRIMARY KEY (AUDIT_PROCESS_ID)
)
GO
----- STATEMENT CREATE TABLE (TO EXECUTE EVERYTIME / AT EACH EXECUTION OF THE SCRIPT)
CREATE SYNONYM SYN_TB_VYB_DMA_AUDIT_PROCESS FOR TB_VYB_DMA_AUDIT_PROCESS
GO