--- Database name:  	DB_VYB_DMA
--- DBMS name:      	Microsoft SQL Server 2017
--- Created on:     	6/12/2019 9:42:18 AM
--- Project Name:	TALOS Integration & Reporting
--- Application:	VyB (Visualize Your Business)
--- DB Layer:		DMA
--- DB Name:		DB_VYB_DMA
--- Author:		Florian Nicolas (External)
--- Description:	Creation of the table TB_VYB_DIM_USER_ME_DT 
--------------------------------------------------------------------
----- STATEMENT DROP TABLE AND SYNONYM IF EXIST
USE DB_VYB_DMA
GO
IF OBJECT_ID('TB_VYB_DIM_USER_ME_DT', 'U') IS NOT NULL
DROP TABLE TB_VYB_DIM_USER_ME_DT
IF OBJECT_ID('SYN_TB_VYB_DIM_USER_ME_DT', 'SN') IS NOT NULL
DROP SYNONYM SYN_TB_VYB_DIM_USER_ME_DT
IF OBJECT_ID('PK_TB_VYB_DIM_USER_ME_DT', 'PK') IS NOT NULL
ALTER TABLE TB_VYB_DIM_USER_ME_DT DROP CONSTRAINT PK_TB_VYB_DIM_USER_ME_DT;
GO
----- STATEMENT CREATE TABLE
USE DB_VYB_DMA
GO
CREATE TABLE TB_VYB_DIM_USER_ME_DT (
   SR_KEY_USER_ME       INT 			NOT NULL,
   BK_KEY_USER_ME       VARCHAR(256)         	NOT NULL,
   USER_ID              VARCHAR(256)         	NOT NULL,
   USER_NM              VARCHAR(256)         	NULL,
   USER_LOGIN_NM        VARCHAR(256)         	NULL,
   USER_EMAIL_NM        VARCHAR(256)         	NULL,
   USER_STATUS_FLAG_NM  VARCHAR(256)         	NULL,
   USER_APPLICATION_ID  VARCHAR(256)         	NULL,
   USER_ACTIVATION_FLG_NM VARCHAR(256)         	NULL,
   USER_PREF_LANGUAGE_NM VARCHAR(256)         	NULL,
   USER_OWNER_NM        VARCHAR(256)         	NULL,
   USER_SURNAME_NM      VARCHAR(256)         	NULL,
   USER_ADDRESS_DSC     VARCHAR(256)         	NULL,
   USER_MOBILE_PHONE_NUM VARCHAR(256)         	NULL,
   USER_NEWSPAGE_CODE   VARCHAR(256)         	NULL,
   USER_PRIORITY_CODE   VARCHAR(256)         	NULL,
   USER_ASSOC_CMS_USER_ID VARCHAR(256)         	NULL,
   TK_KEY_VLD_FM_DT     SMALLDATETIME		NULL,
   TK_KEY_VLD_TO_DT     SMALLDATETIME		NULL,
   TK_KEY_AUDIT_PROCESS_ID_INS INT		NULL,
   TK_KEY_AUDIT_PROCESS_ID_UPD INT		NULL,
   TK_KEY_INL_PPN_TMS   SMALLDATETIME		NULL,
   TK_KEY_LAST_PPN_TMS  SMALLDATETIME		NULL,
   TK_KEY_UNQ_ID_SRC_STM VARCHAR(256)		NULL,
   TK_KEY_LAST_VSN_FL   BIT			NULL,
   TK_KEY_HASH_VALUE    VARCHAR(256)		NULL,
   TK_KEY_PROJECT_CD    VARCHAR(256)		NULL,
   CONSTRAINT PK_TB_VYB_DIM_USER_ME_DT PRIMARY KEY NONCLUSTERED (SR_KEY_USER_ME)
)
GO
IF EXISTS (SELECT 1 FROM  SYS.EXTENDED_PROPERTIES
           WHERE MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT') AND MINOR_ID = 0)
BEGIN 
   DECLARE @CURRENTUSER SYSNAME 
SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description',  
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT' 
END 
SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description',  
   '- Client Name: Philip Morris International
   - Client Location: Dubai (UAE)
   - Application Name: VyB (Visualize Your Business)
   - Client Location: Dubai (UAE)
   - Application Description: VyB is BI application that enable to load internal PMI data from the source system to last DB layer in order to build data reports and interactive data visualization applications. The data reports and data visualizations applications are developed for internal use.
   - Component Type: Entity
   - Component Name: Table User ME
   - Specific Project / Application Source Code: TALOS', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'SR_KEY_USER_ME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'SR_KEY_USER_ME'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Surrogate Key User ME',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'SR_KEY_USER_ME'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'BK_KEY_USER_ME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'BK_KEY_USER_ME'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Business Key User ME',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'BK_KEY_USER_ME'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'USER_ID')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_ID'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Identifier',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_ID'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'USER_NM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_NM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Name',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_NM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'USER_LOGIN_NM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_LOGIN_NM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Login',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_LOGIN_NM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'USER_EMAIL_NM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_EMAIL_NM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Email',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_EMAIL_NM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'USER_STATUS_FLAG_NM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_STATUS_FLAG_NM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Account Status Name',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_STATUS_FLAG_NM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'USER_APPLICATION_ID')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_APPLICATION_ID'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Account Flag Registered From Application',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_APPLICATION_ID'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'USER_ACTIVATION_FLG_NM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_ACTIVATION_FLG_NM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Account Flag Activation',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_ACTIVATION_FLG_NM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'USER_PREF_LANGUAGE_NM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_PREF_LANGUAGE_NM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Account Prefered Language',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_PREF_LANGUAGE_NM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'USER_OWNER_NM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_OWNER_NM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Account Owner Name',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_OWNER_NM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'USER_SURNAME_NM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_SURNAME_NM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Account Surname',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_SURNAME_NM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'USER_ADDRESS_DSC')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_ADDRESS_DSC'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Account Address',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_ADDRESS_DSC'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'USER_MOBILE_PHONE_NUM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_MOBILE_PHONE_NUM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Account Mobile Phone Number',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_MOBILE_PHONE_NUM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'USER_NEWSPAGE_CODE')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_NEWSPAGE_CODE'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Account Newspage Code',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_NEWSPAGE_CODE'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'USER_PRIORITY_CODE')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_PRIORITY_CODE'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Account Priority ',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_PRIORITY_CODE'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'USER_ASSOC_CMS_USER_ID')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_ASSOC_CMS_USER_ID'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'User Account CMS User',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'USER_ASSOC_CMS_USER_ID'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TK_KEY_VLD_FM_DT')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_VLD_FM_DT'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Technical Key Valid From Date',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_VLD_FM_DT'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TK_KEY_VLD_TO_DT')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_VLD_TO_DT'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Technical Key Valid To Date',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_VLD_TO_DT'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TK_KEY_AUDIT_PROCESS_ID_INS')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_AUDIT_PROCESS_ID_INS'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Technical Key Link To Auditing Process Table Record Created',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_AUDIT_PROCESS_ID_INS'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TK_KEY_AUDIT_PROCESS_ID_UPD')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_AUDIT_PROCESS_ID_UPD'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Technical Key Link To Auditing Process Table Record Update',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_AUDIT_PROCESS_ID_UPD'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TK_KEY_INL_PPN_TMS')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_INL_PPN_TMS'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Technical Key Record Creation Timestamp',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_INL_PPN_TMS'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TK_KEY_LAST_PPN_TMS')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_LAST_PPN_TMS'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Technical Key Record Update Timestamp',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_LAST_PPN_TMS'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TK_KEY_UNQ_ID_SRC_STM')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_UNQ_ID_SRC_STM'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Technical Key Concatenated Value All Primary Key Columns Plus Separators',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_UNQ_ID_SRC_STM'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TK_KEY_LAST_VSN_FL')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_LAST_VSN_FL'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Technical Key Boolean Indicating if Record is the Last Version or Not',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_LAST_VSN_FL'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TK_KEY_HASH_VALUE')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_HASH_VALUE'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Technical Key Hash-value All Non-Technical Columns in the Table',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_HASH_VALUE'
GO
IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('TB_VYB_DIM_USER_ME_DT')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'TK_KEY_PROJECT_CD')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_PROJECT_CD'
END
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'Technical Key Project Code',
   'user', @CURRENTUSER, 'table', 'TB_VYB_DIM_USER_ME_DT', 'column', 'TK_KEY_PROJECT_CD'
GO
----- STATEMENT CREATE TABLE
CREATE SYNONYM SYN_TB_VYB_DIM_USER_ME_DT FOR TB_VYB_DIM_USER_ME_DT
GO