/*==============================================================*/
/* Database name:  DB_VYB_DMA                                   */
/* DBMS name:      Microsoft SQL Server 2017                    */
/* Created on:     6/12/2019 12:40:24 AM                        */
/*==============================================================*/


DROP DATABASE DB_VYB_DMA
go

/*==============================================================*/
/* Database: DB_VYB_DMA                                         */
/*==============================================================*/
CREATE DATABASE DB_VYB_DMA
go

USE DB_VYB_DMA
go

ISQL TB_VYB_AUDIT_PROCESS.sql
go

ISQL TB_VYB_DIM_DATE_H.sql
go

ISQL TB_VYB_DIM_EVENT_TYPE_H.sql
go

ISQL TB_VYB_DIM_LOCATION_H.sql
go

ISQL TB_VYB_DIM_TRANSACTION_TYPE_H.sql
go

ISQL TB_VYB_DIM_UNIT_TYPE_H.sql
go

ISQL TB_VYB_DIM_USER_ME_H.sql
go

ISQL TB_VYB_DIM_USER_POS_H.sql
go

ISQL TB_VYB_DIM_USER_SUP_H.sql
go

ISQL TB_VYB_FACT_AMNT_POINT_H.sql
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_DT_CRT_TRANSAC)
      REFERENCES TB_VYB_DIM_DATE_H (SR_KEY_DATE)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_DT_CRT_USER_ME)
      REFERENCES TB_VYB_DIM_DATE_H (SR_KEY_DATE)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_DT_CRT_USER_POS)
      REFERENCES TB_VYB_DIM_DATE_H (SR_KEY_DATE)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_DT_CRT_USER_SUP)
      REFERENCES TB_VYB_DIM_DATE_H (SR_KEY_DATE)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_DT_UPD_USER_SUP)
      REFERENCES TB_VYB_DIM_DATE_H (SR_KEY_DATE)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_DT_UPD_TRANSAC)
      REFERENCES TB_VYB_DIM_DATE_H (SR_KEY_DATE)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_DT_UPD_USER_ME)
      REFERENCES TB_VYB_DIM_DATE_H (SR_KEY_DATE)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_DT_UPD_USER_POS)
      REFERENCES TB_VYB_DIM_DATE_H (SR_KEY_DATE)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_EVENT_TYPE)
      REFERENCES TB_VYB_DIM_EVENT_TYPE_H (SR_KEY_EVENT_TYPE)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_LOCATION_USER_ME)
      REFERENCES TB_VYB_DIM_LOCATION_H (SR_KEY_LOCATION)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_LOCATION_USER_POS)
      REFERENCES TB_VYB_DIM_LOCATION_H (SR_KEY_LOCATION)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_LOCATION_USER_SUP)
      REFERENCES TB_VYB_DIM_LOCATION_H (SR_KEY_LOCATION)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_TRANSACTION_TYPE)
      REFERENCES TB_VYB_DIM_TRANSACTION_TYPE_H (SR_KEY_TRANSACTION_TYPE)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_UNIT_TYPE)
      REFERENCES TB_VYB_DIM_UNIT_TYPE_H (SR_KEY_UNIT_TYPE)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_USER_ME)
      REFERENCES TB_VYB_DIM_USER_ME_H (SR_KEY_USER_ME)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_USER_POS)
      REFERENCES TB_VYB_DIM_USER_POS_H (SR_KEY_USER_POS)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ALTER TABLE TB_VYB_FACT_AMNT_POINT_H
   ADD CONSTRAINT FK_TB_VYB_F_LINK_TABL_TB_VYB_D FOREIGN KEY (SR_KEY_USER_SUP)
      REFERENCES TB_VYB_DIM_USER_SUP_H (SR_KEY_USER_SUP)
         ON UPDATE CASCADE ON DELETE CASCADE
go

ISQL SYN_TB_VYB_DIM_DATE_H.sql
go

ISQL SYN_TB_VYB_DIM_EVENT_TYPE_H.sql
go

ISQL SYN_TB_VYB_DIM_LOCATION_H.sql
go

ISQL SYN_TB_VYB_DIM_TRANSACTION_TYPE_H.sql
go

ISQL SYN_TB_VYB_DIM_UNIT_TYPE_H.sql
go

ISQL SYN_TB_VYB_DIM_USER_ME_H.sql
go

ISQL SYN_TB_VYB_DIM_USER_POS_H.sql
go

ISQL SYN_TB_VYB_DIM_USER_SUP_H.sql
go

ISQL SYN_TB_VYB_FACT_AMNT_POINT_H.sql
go

